### ISSUE TITLE
Statamic peak forms and turnstile

### ISSUE THREAD

**Issue by freshface** [aryehraber/statamic-captcha#59] opened 2024-11-18 21:52 UTC
I am using this addon for a lot of projects.
But it breaks when using alpine and precognition.
It would be great if the plugin also works with that.

I am using peak as a starter kit, which uses precognution.

**Comment by aryehraber** [comment] 2024-11-19 07:21
Hi @freshface, glad to hear that Captcha has been useful to you so far! 🙌

Thanks for the bug report, I'll try and set up a project and see what's going on when I next have a moment.

If you are able to provide a simple project that has the starter kit and everything ready to go, that'd really help speed up reproducing the issue on my end to help debug.

**Comment by gml-fahlgren** [comment] 2024-11-25 18:25
I'm having the same difficulty. My company has a number of Statamic sites all using the Peak starter which in turn use Alpine.js and Precognition, and I'm unable to get the Captcha add-on to work with any of them; Google's dashboard says that the captchas have detected no bots, but I consistently get a 422 "captcha failed" error upon form submission on any of the sites where I've tried to install this.

**Comment by aryehraber** [comment] 2024-11-26 15:26
Hi @freshface & @gml-fahlgren,

I had some time to play around with Peak and got it working with Turnstile!

Since Peak uses Alpine.js to submit forms, as you mentioned, the standard method that these captcha snippets use doesn't work (hence why you are seeing failing captchas).

--- 

First, I added Captcha as usual (in the head, and inside the Statamic form itself as per the docs).

Next, I published Peak's views using:
```
php artisan vendor:publish --tag="statamic-peak-tools-views"
```
This should add some new files to `resources/views/vendor/statamic-peak-tools`. 

Next, I opened the `_form_handler` snippet from the above published files, and added the following line at the top of the submit method:

```js
this.form['cf-turnstile-response'] = this.$refs.form.querySelector('.cf-turnstile input')?.value
```

So it should looks something like:

```js
submit() {
    this.form['cf-turnstile-response'] = this.$refs.form.querySelector('.cf-turnstile input')?.value

    this.submitted = true

    // rest of code...
```

Finally, I had to add the additional data property to the `form:create` tag, as per the [Peak docs](https://peak.1902.studio/features/forms.html#submit-additional-data):

```antlers
x-data='@{"cf-turnstile-response": "" }'
```

So the Statamic form tag should look something like:

```antlers
{{ form:create :in="form:handle" js="alpine:form" attr:x-ref="form" x-data='@{"cf-turnstile-response": "" }' }}
```

After the above changes everything seemed to be working (assuming the Captcha config is setup correctly + the Turnstile site key & secret are set).

Hope this helps, let me know if you have any additional questions!

p.s. once you report back, I'll do my best to update the docs to make this easierin the future.

**Comment by aryehraber** [comment] 2024-11-26 17:03
@webcodecs That's great to hear 🙌  Yeah, the captcha input query selector requires some tweaking per service -- will have a think if I can make this simpler from the addon's side, otherwise I'll just list each one once I update the docs (thanks for the hCaptcha one 👍).

**Comment by gml-fahlgren** [comment] 2024-11-26 17:44
I've confirmed that this works with reCAPTCHA with `this.form['g-recaptcha-response'] = this.$refs.form.querySelector('.g-recaptcha-response')?.value`. Thank you!

**Comment by aryehraber** [comment] 2024-11-26 17:47
@gml-fahlgren Awesome 🎉

**Comment by freshface** [comment] 2024-11-26 18:24
Nice one! Will test it out

**Comment by robdekort** [comment] 2024-11-26 19:34
Hey folks. Wanted to to let you know that @aryehraber reached out today regarding this issue. We'll try to pair soon to make this easier going forward, or at least update the Peak docs with instructions on how to make this compatible.

**Comment by aryehraber** [comment] 2024-11-29 10:48
Hi everyone! @robdekort and I had a chat this morning and came up with a much easier solution for Peak + Captcha integration going forward 🚀  

A new version of Captcha has been released (v1.14.0) and a new version of Peak Tools will also be released soon. These updates will allow you to only add `x-data='@{"captcha-response": "" }'` to your Statamic form tag (+ the usual Captcha installation steps) and no longer require publishing and editing the Peak Tools vendor files, nor will you need to edit the query selector for each captcha provider (this is handled automatically). 

Once the final PRs are merged, @robdekort will update the Peak docs to reflect the above.

If there's any issues or feedback, please let us know!

**Closed by aryehraber** 2024-11-29 10:48 UTC

**Comment by robdekort** [comment] 2024-11-29 10:52
The tools addon also just got the update and the new docs are online as well. 

Lovely stuff!

**Comment by shmdesign** [comment] 2024-12-06 12:17
Hello All,

Can someone explain how to do this purely with alpinejs and the basic example from statamic? 

I have tried and follow each steps but I still do get a ```400 (Bad Request)``` and this is the response I get:
```{
     "errors": [
          "Captcha failed."
      ],
      "error": {
           "captcha":"Captcha failed."
      }
}```

Thanks all

**Comment by aryehraber** [comment] 2024-12-07 14:32
@shmdesign Do you mean you're not using Peak? Just implementing Alpine.js yourself?

If so, take a look at the minor changes that were made to the Peak Tools view snippet to push the Captcha value into the Alpine.js data object before submission: https://github.com/studio1902/statamic-peak-tools/blob/main/resources/views/snippets/_form_handler.antlers.html#L39-L41 This of course assumes you've added `"captcha-response": ""` to the form object.

**Comment by eliottchampault** [comment] 2024-12-09 10:38
Thank you for you response.

Here is what I did as a non peak user for anyone who is trying to do the same.

Following the steps from [statamic](https://statamic.dev/forms#precognition), your ```form``` should look a bit like this:
```
<div x-data='{
    form: $form(
        "post",
        $refs.form.getAttribute("action"),
        JSON.parse($refs.form.getAttribute("x-data"))
    ), 
    init() {
        $refs.form.addEventListener("submit", evt => {
            evt.preventDefault();
            this.form.submit().then(response => {
                this.form.reset();
                console.log("Success")
            }).catch(error => {
                console.log(error);
            });
        });
    } 
}'>
```

You need to replace 
```
form: $form(
        "post",
        $refs.form.getAttribute("action"),
        JSON.parse($refs.form.getAttribute("x-data"))
    ), 
```
by 
```
form: $form(
        "post",
        $refs.form.getAttribute("action"),
        {{# Modified x-data to include "captcha-response": "" #}}
        {
               ...JSON.parse($refs.form.getAttribute("x-data")),
               "captcha-response": ""
        }
), 
```

and then replace
```
 init() {
        $refs.form.addEventListener("submit", evt => {
            evt.preventDefault();
            this.form.submit().then(response => {
                this.form.reset();
                console.log("Success")
            }).catch(error => {
                console.log(error);
            });
        });
 }
```
by
```
 init() {
        $refs.form.addEventListener("submit", evt => {
            evt.preventDefault();

           {{# Add these here #}}
            if (Object.keys(this.form).includes("captcha-response")) {
                   this.form["captcha-response"] = this.$refs.form.querySelector("{{ captcha:selector }}")?.value
            }
            this.form.submit().then(response => {
                this.form.reset();
                console.log("Success")
            }).catch(error => {
                console.log(error);
            });
        });
 } 
``` 

I hope this helps.

All the best
